//This code was generated by a tool.
//Changes to this file will be lost if the code is regenerated.
// See the blog post here for help on using the generated code: http://erikej.blogspot.dk/2014/10/database-first-with-sqlite-in-universal.html
using Microsoft.Data.Sqlite;
using System.Data.SQLite;
using System;
using ServiceStack.DataAnnotations;
using Hangfire.Annotations;

namespace TextStatistics
{
    public class SQLiteDb
    {
        string _path;
        public SQLiteDb(string path)
        {
            _path = path;
        }
        
        // public void Create()
        //{
        //    using (SQLiteConnection db = new SQLiteConnection(_path))
        //    {
        //        db.CreateTable<Author>();
        //        db.CreateTable<Book>();
        //        db.CreateTable<Frequency>();
        //        db.CreateTable<Words>();
        //    }
        //}
    }
    public partial class Author
    {
        [PrimaryKey, AutoIncrement]
        public Int64 AuthorId { get; set; }
        
        [NotNull]
        public String Name { get; set; }
        
        [NotNull]
        public String Surname { get; set; }
        
    }
    
    public partial class Book
    {
        [PrimaryKey, AutoIncrement]
        public Int64 BookId { get; set; }
        
        [NotNull]
        public String Title { get; set; }
        
        [NotNull]
        public Int64 AuthorId { get; set; }
        
    }
    
    public partial class Frequency
    {
        [PrimaryKey, AutoIncrement]
        public Int64 FrequencyId { get; set; }
        
        [NotNull]
        public Int64 WordCounter { get; set; }
        
    }
    
    public partial class Words
    {
        [PrimaryKey, AutoIncrement]
        public Int64 WordId { get; set; }
        
        [NotNull]
        public Int64 BookId { get; set; }
        
        [NotNull]
        public Int64 FrequencyId { get; set; }
        
        [NotNull]
        public String Word { get; set; }
        
    }
    
}
